#@TYPE: Machine
#@NAME: RaspberryPi 4 Development Board (64bit) - mima layer override
#@DESCRIPTION: Custom machine configuration for the RaspberryPi 4 in the meta-mima layer.

require ${LAYERDIR}/../meta-raspberrypi/conf/machine/raspberrypi4-64.conf

ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
GPU_MEM = "16"
